Feature/refactoring sass
tepy-pr/kenshu-frontend pull request #3
Opened 2021-03-05 03:27 UTC by tepy-pr

### 目的
Sassにリファクタリングをする。

### 行ったこと

- 　`node-sass`のコンパイル過程を導入
- 　`stylelint`設定（`PR TIMES`の）を導入
- 　`Block`や`Mixin`にスタイルを分別
- 　要素やCSS変数などの命名を`PR TIMES`の規則による変更
- 　色の命名をコンポーネントによるの名前ではなく、`Style System`の`Color Palette`のように命名を付けた

### 感想

- `prettier`を利用しましたので、自動的に`leading-zero`に書かされるので（`disable`設定がない）、今回の`stylelint`の結果は`leading-zero`のエラーが出ています。
- `#f2f2f2`と`#f1f1f1`の色を利用しましたところ、結構似ているので同じ色にしても良いのかなと思いました。
- `sass`の`@each`などの昨日をカードの`thumbnail`の`background-image`として自動的に作ろうと思いましたが、実際の時に、`fetch`した画像の`url`をCSSに書き込むのは良くないかなと思って、`@each`を利用しませんでした。

2021-03-08 06:32 UTC, pr-YudaiSuzuki requested changes
1点コメントしたのでご確認ください。

また、`mixin` は使わなくても実装できるものなので、今回の研修のような規模だと必要性が低いです。ただ、練習として使ってみるのはとても良いことだと思います。

`mixin` を使う場面としてはレスポンシブ対応するときのメディアクエリや、ベンダープレフィックスを付ける際は効果的かと思います。

2021-03-08 06:32 UTC, pr-YudaiSuzuki commented on src/scss/blocks/_sidebar.scss
> +.sidebar-item__title {
Block が存在しない箇所に Element の定義がされています。
`.sidebar-item` Block を作ってあげましょう。

2021-03-09 01:09 UTC, tepy-pr commented
@pr-YudaiSuzuki 
コメントありがとうございます。

Blockを追加しましたので、ご確認お願いいたします。

2021-03-09 01:12 UTC, pr-YudaiSuzuki approved these changes
LGTMです！

2021-03-09 01:47 UTC, merged